version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - errcheck
    - gosec
    - misspell
    - staticcheck
  settings:
    gosec:
      excludes:
        - G301  # directory permissions
        - G306  # file permissions
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
