version: 2
project_name: fedramp-tui

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: ethanolivertroy
    name: fedramp-tui

brews:
  - repository:
      owner: ethanolivertroy
      name: homebrew-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/ethanolivertroy/fedramp-tui
    description: Terminal UI for browsing FedRAMP documentation
    license: MIT
    test: |
      system "#{bin}/fedramp-tui", "--help"
